server:
  port: ${PORT:8080}

base-url: /api

spring:
  application:
    name: taskManager

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger.html