server:
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

    liquibase:
      enabled: false
      change-log: classpath:db/changelog/changelog-master.xml

  jpa:
    show-sql: false

logging:
  level:
    ROOT: INFO