server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: 'jdbc:h2:./taskManager'
    username: ''
    password: ''
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#
#    liquibase:
#      enabled: true
#      change-log: classpath:db/changelog/changelog-master.xml

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE
    # org.springframework.security: TRACE
    # io.hexlet.typoreporter: DEBUG